# Dependent action: GIthubActionSendEmail

# each of the yml is called "actions" or "workflow" file. 

name: follower-notifier
on:
  schedule: #what is this?
    - cron: '0 3 * * *' # notify me daily, in UTC time (google: create a RE for cron statement)
jobs:
  main:
    runs-on: ubuntu-latest # It is a runner choice. Don't need to change it. 
    steps: # This is the keyword that group together all the steps in this job object. 
      - name: get follower change # an optional name of a sub-workflow
        id: followerChange # What is ID?
        uses: Sorosliu1029/follower-change@v2   
        # first attribute: github username. 
        # second attribute: repository name under that user. 
        # @N: the version of a repository
        with:
          myToken: ${{ secrets.MY_TOKEN }}
          notifyUnFollowEvent: true
      - name: email me
        uses: dawidd6/action-send-mail@v3
        if: steps.followerChange.outputs.shouldNotify == 'true'
        with:
          server_address: smtp.gmail.com # for tencent user, smtp.qq.com
          server_port: 465 
          username: ${{ secrets.MAIL_USERNAME }} # You need to create 
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: GitHub Follower Change
          from: Follower Change Notifier
          to: ${{ secrets.TO_EMAIL_ADDRESS }}
          # use html file from previous step as email body
          html_body: file://${{ steps.followerChange.outputs.htmlFilePath }}
